import { Router } from "express";
import { AuthRoutes } from "../module/auth/auth.route.js";
import { UserRoutes } from "../module/user/user.route.js";
import { MentorRoutes } from "../module/mentor/mentor.route.js";
import { BookingRoutes } from "../module/booking/booking.route.js";
import { ReviewRoutes } from "../module/review/review.route.js";
import { AIRoutes } from "../module/ai/ai.route.js";
import { AnalyticsRoutes } from "../module/analytics/analytics.route.js";
import { NotificationRoutes } from "../module/notification/notification.route.js";

const router = Router();
router.use("/auth", AuthRoutes);
router.use("/users", UserRoutes);
router.use("/mentors", MentorRoutes);
router.use("/bookings", BookingRoutes);
router.use("/reviews", ReviewRoutes);
router.use("/ai", AIRoutes);
router.use("/analytics", AnalyticsRoutes);
router.use("/notifications", NotificationRoutes);
export const IndexRoutes = router;
